name: Deploy to Azure

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure
      run: |
        az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
        az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Deploy ARM Template
      run: |
        az deployment group create --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --template-file azuredeploy.json --parameters @azuredeploy.parameters.json

    - name: Get Publish Profile for Receive Log Function
      run: |
        az webapp deployment list-publishing-profiles --name logservice-fa-receive-log --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --output json > publishProfileReceiveLog.json
        publish_profile=$(jq -r '.[0].publishProfile' publishProfileReceiveLog.json)
        echo "PUBLISH_PROFILE_RECEIVE_LOG=\"$publish_profile\"" >> $GITHUB_ENV

    - name: Get Publish Profile for Retrieve Log Function
      run: |
        az webapp deployment list-publishing-profiles --name logservice-fa-retrieve-log --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --output json > publishProfileRetrieveLog.json
        publish_profile=$(jq -r '.[0].publishProfile' publishProfileRetrieveLog.json)
        echo "PUBLISH_PROFILE_RETRIEVE_LOG=\"$publish_profile\"" >> $GITHUB_ENV

    - name: Debug Environment Variables
      run: |
        echo "FUNCTION_APP_NAME_RECEIVE_LOG: logservice-fa-receive-log"
        echo "PUBLISH_PROFILE_RECEIVE_LOG: ${{ env.PUBLISH_PROFILE_RECEIVE_LOG }}"
        echo "FUNCTION_APP_NAME_RETRIEVE_LOG: logservice-fa-retrieve-log"
        echo "PUBLISH_PROFILE_RETRIEVE_LOG: ${{ env.PUBLISH_PROFILE_RETRIEVE_LOG }}"

    - name: Deploy Receive Log Function to Azure
      uses: Azure/functions-action@v1
      with:
        app-name: logservice-fa-receive-log
        package: "./ReceiveLogEntry"
        publish-profile: ${{ env.PUBLISH_PROFILE_RECEIVE_LOG }}

    - name: Deploy Retrieve Log Function to Azure
      uses: Azure/functions-action@v1
      with:
        app-name: logservice-fa-retrieve-log
        package: "./RetrieveLogEntries"
        publish-profile: ${{ env.PUBLISH_PROFILE_RETRIEVE_LOG }}