name: Deploy to Azure

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure
      run: |
        az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
        az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Create Resource Group
      run: |
        az group create --name ${{ secrets.resourceGroup }} --location "North Europe"

    - name: Generate Unique Suffix
      id: suffix
      run: echo "suffix=$(openssl rand -hex 4)" >> $GITHUB_ENV

    - name: Deploy ARM Template
      run: |
        az deployment group create --resource-group ${{ secrets.resourceGroup }} --template-file azuredeploy.json --parameters storageAccountName=storweqa${{ env.suffix }} --parameters @azuredeploy.parameters.json

    - name: Deploy Receive Log Function to Azure
      run: |
        zip -r ReceiveLogEntry.zip ./ReceiveLogEntry
        az functionapp deployment source config-zip -g ${{ secrets.resourceGroup }} -n ${{ secrets.FUNCTION_APP_NAME_RECEIVE_LOG }} --src ReceiveLogEntry.zip

    - name: Deploy Retrieve Log Function to Azure
      run: |
        zip -r RetrieveLogEntries.zip ./RetrieveLogEntries
        az functionapp deployment source config-zip -g ${{ secrets.resourceGroup }} -n ${{ secrets.FUNCTION_APP_NAME_RETRIEVE_LOG }} --src RetrieveLogEntries.zip

    - name: Set Environment Variables for Function App Names
      run: |
        echo "FUNCTION_APP_NAME_RECEIVE_LOG=$(terraform output -raw function_app_name_receive_log)" >> $GITHUB_ENV
        echo "FUNCTION_APP_NAME_RETRIEVE_LOG=$(terraform output -raw function_app_name_retrieve_log)" >> $GITHUB_ENV
      working-directory: ./terraform

    - name: Get Publish Profile for Receive Log Function
      run: |
        az webapp deployment list-publishing-profiles --name ${{ env.FUNCTION_APP_NAME_RECEIVE_LOG }} --resource-group ${{ secrets.resourceGroup }} --output tsv > publishProfileReceiveLog.txt
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Get Publish Profile for Retrieve Log Function
      run: |
        az webapp deployment list-publishing-profiles --name ${{ env.FUNCTION_APP_NAME_RETRIEVE_LOG }} --resource-group ${{ secrets.resourceGroup }} --output tsv > publishProfileRetrieveLog.txt
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Debug Environment Variables
      run: |
        echo "FUNCTION_APP_NAME_RECEIVE_LOG: ${{ env.FUNCTION_APP_NAME_RECEIVE_LOG }}"
        echo "FUNCTION_APP_NAME_RETRIEVE_LOG: ${{ env.FUNCTION_APP_NAME_RETRIEVE_LOG }}"