name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure
      run: |
        az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
        az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Create Resource Group
      run: |
        az group create --name ${{ secrets.resourceGroup }} --location "North Europe"

    - name: Generate Unique Suffix
      id: suffix
      run: echo "suffix=$(openssl rand -hex 4)" >> $GITHUB_ENV

    - name: Create Cosmos DB Account
      run: |
        cosmosDbAccountName="cosmosdb${{ env.suffix }}"
        az cosmosdb create --name $cosmosDbAccountName --resource-group ${{ secrets.resourceGroup }} --kind GlobalDocumentDB --locations regionName='North Europe' failoverPriority=0 isZoneRedundant=False
        echo "COSMOS_DB_ACCOUNT_NAME=$cosmosDbAccountName" >> $GITHUB_ENV

    - name: Deploy ARM Template
      run: |
        az deployment group create --resource-group ${{ secrets.resourceGroup }} --template-file azuredeploy.json --parameters storageAccountName=storweqa${{ env.suffix }} --parameters @azuredeploy.parameters.json

    - name: Retrieve Cosmos DB Connection String
      run: |
        cosmosDbConnectionString=$(az cosmosdb keys list --name ${{ env.COSMOS_DB_ACCOUNT_NAME }} --resource-group ${{ secrets.resourceGroup }} --type connection-strings --query "connectionStrings[0].connectionString" -o tsv)
        echo "COSMOS_DB_CONNECTION_STRING=$cosmosDbConnectionString" >> $GITHUB_ENV

    - name: Deploy Receive Log Function to Azure
      run: |
        zip -r ReceiveLogEntry.zip ./ReceiveLogEntry
        az functionapp deployment source config-zip -g ${{ secrets.resourceGroup }} -n ${{ secrets.FUNCTION_APP_NAME_RECEIVE_LOG }} --src ReceiveLogEntry.zip

    - name: Deploy Retrieve Log Function to Azure
      run: |
        zip -r RetrieveLogEntries.zip ./RetrieveLogEntries
        az functionapp deployment source config-zip -g ${{ secrets.resourceGroup }} -n ${{ secrets.FUNCTION_APP_NAME_RETRIEVE_LOG }} --src RetrieveLogEntries.zip

    - name: Get Publish Profile for Receive Log Function
      run: |
        az webapp deployment list-publishing-profiles --name ${{ secrets.FUNCTION_APP_NAME_RECEIVE_LOG }} --resource-group ${{ secrets.resourceGroup }} --output tsv > publishProfileReceiveLog.txt
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: View Publish Profile Receive Log
      run: cat publishProfileReceiveLog.txt

    - name: Get Publish Profile for Retrieve Log Function
      run: |
        az webapp deployment list-publishing-profiles --name ${{ secrets.FUNCTION_APP_NAME_RETRIEVE_LOG }} --resource-group ${{ secrets.resourceGroup }} --output tsv > publishProfileRetrieveLog.txt
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: View Publish Profile Retrieve Log
      run: cat publishProfileRetrieveLog.txt

    - name: Upload Publish Profile Receive Log
      uses: actions/upload-artifact@v2
      with:
        name: publishProfileReceiveLog
        path: publishProfileReceiveLog.txt

    - name: Upload Publish Profile Retrieve Log
      uses: actions/upload-artifact@v2
      with:
        name: publishProfileRetrieveLog
        path: publishProfileRetrieveLog.txt